// Auto-generated from ALL visual audits of 0530 baseline vs 0605/0606 mapped candidates.
// Impact grades rechecked using playbook: memory/60_Playbooks/competitor_screenshot_impact_grading.md
// Stable/no-obvious-change rows are forced to low unless a concrete conversion-path/module-shift is stated.

export const strictChangeRows = [
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0011",
    "reviewId": "R0041",
    "dimension": "消金",
    "page": "首页频道-推荐",
    "conclusion": "首页/618同视口，顶部额度区一致，中部营销从商品促销切换为会员、审批服务、返券等权益模块。",
    "process": "页面事实：首页/618同视口，顶部额度区一致，中部营销从商品促销切换为会员、审批服务、返券等权益模块。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "中",
    "managementUsable": true,
    "managementNote": "618首页营销位偏向会员权益、审批服务和金融促活。（影响等级复核：中）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0011/R0041_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0011/R0041_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0031",
    "reviewId": "R0045",
    "dimension": "客服",
    "page": "首页推荐页",
    "conclusion": "首页/618同视口，商品促销位变为满减返券、审批服务、618返券等金融/权益模块。",
    "process": "页面事实：首页/618同视口，商品促销位变为满减返券、审批服务、618返券等金融/权益模块。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "中",
    "managementUsable": true,
    "managementNote": "首页大促内容策略转向金融权益与返券。（影响等级复核：中）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0031/R0045_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0031/R0045_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0032",
    "reviewId": "R0046",
    "dimension": "客服",
    "page": "首页推荐页",
    "conclusion": "首页/618同视口，商品促销切换为影音会员、审批服务、满减返券等权益模块。",
    "process": "页面事实：首页/618同视口，商品促销切换为影音会员、审批服务、满减返券等权益模块。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "中",
    "managementUsable": true,
    "managementNote": "权益和金融服务权重上升。（影响等级复核：中）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0032/R0046_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0032/R0046_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0038",
    "reviewId": "R0048",
    "dimension": "客服",
    "page": "首页推荐页",
    "conclusion": "首页同视口，618活动位从家居/大牌满额等重排为超市金、审批、提额、笔笔返等。",
    "process": "页面事实：首页同视口，618活动位从家居/大牌满额等重排为超市金、审批、提额、笔笔返等。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "中",
    "managementUsable": true,
    "managementNote": "618营销资源位转向金融权益。（影响等级复核：中）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0038/R0048_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0038/R0048_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0001",
    "reviewId": "R0170",
    "dimension": "消金",
    "page": "首页首屏",
    "conclusion": "首页/推荐同视口，顶部额度区一致，中部618宫格、商品/权益卡片大幅替换。",
    "process": "页面事实：首页/推荐同视口，顶部额度区一致，中部618宫格、商品/权益卡片大幅替换。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "首页营销资源位、618活动配置和商品推荐调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0001/R0170_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0001/R0170_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0003",
    "reviewId": "R0055",
    "dimension": "风控",
    "page": "借款额度/激活页",
    "conclusion": "灵活借首页同视口，授信额度、激活按钮、借款指南、功能入口基本一致。",
    "process": "页面事实：灵活借首页同视口，授信额度、激活按钮、借款指南、功能入口基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "借贷首页核心转化链路稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0003/R0055_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0003/R0055_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0004",
    "reviewId": "R0026",
    "dimension": "消金",
    "page": "借款页下滑/品牌背书",
    "conclusion": "灵活借首页同视口，主体布局与内容基本一致，仅状态栏/消息角标轻微变化。",
    "process": "页面事实：灵活借首页同视口，主体布局与内容基本一致，仅状态栏/消息角标轻微变化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "借款首页核心转化链路稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0004/R0026_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0004/R0026_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0005",
    "reviewId": "R0056",
    "dimension": "消金",
    "page": "购物商城/618活动页",
    "conclusion": "首页推荐流同视口，618会场、搜索词、商品卡片与促销模块替换。",
    "process": "页面事实：首页推荐流同视口，618会场、搜索词、商品卡片与促销模块替换。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "首页大促资源位与商品推荐策略更新。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0005/R0056_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0005/R0056_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0006",
    "reviewId": "R0031",
    "dimension": "客服",
    "page": "消息一级页",
    "conclusion": "消息页同视口，0605优惠消息与未读红点/列表内容有更新。",
    "process": "页面事实：消息页同视口，0605优惠消息与未读红点/列表内容有更新。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "优惠营销消息触达增强。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0006/R0031_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0006/R0031_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0007",
    "reviewId": "R0024",
    "dimension": "风控",
    "page": "消息一级页-下滑一屏",
    "conclusion": "消息页同视口，0605消息分类/选中态与消息列表、未读提示有变化。",
    "process": "页面事实：消息页同视口，0605消息分类/选中态与消息列表、未读提示有变化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "消息触达与优惠活动曝光有调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0007/R0024_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0007/R0024_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0008",
    "reviewId": "R0027",
    "dimension": "消金",
    "page": "我的一级页",
    "conclusion": "我的页同入口同顶部视口，0605内容更偏购物/商品推荐流，服务模块展示弱化。",
    "process": "页面事实：我的页同入口同顶部视口，0605内容更偏购物/商品推荐流，服务模块展示弱化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "个人中心商业化/导购曝光增强。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0008/R0027_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0008/R0027_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0009",
    "reviewId": "R0058",
    "dimension": "风控",
    "page": "我的页下滑/个人中心",
    "conclusion": "我的页顶部视口，账号信息区、功能卡片、书城/推荐商品区域布局与商品内容有调整。",
    "process": "页面事实：我的页顶部视口，账号信息区、功能卡片、书城/推荐商品区域布局与商品内容有调整。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "个人中心运营位和商品推荐内容更新。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0009/R0058_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0009/R0058_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0013",
    "reviewId": "R0217",
    "dimension": "消金",
    "page": "首页快捷入口-PLUS服务",
    "conclusion": "PLUS服务页同首屏视口，布局、权益模块、价格与开通按钮基本一致。",
    "process": "页面事实：PLUS服务页同首屏视口，布局、权益模块、价格与开通按钮基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "PLUS会员页视觉稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0013/R0217_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0013/R0217_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0014",
    "reviewId": "R0054",
    "dimension": "消金",
    "page": "充值中心/卡券支付页",
    "conclusion": "充值中心同视口，套餐与热门充值入口基本一致，金额档位展示有轻微差异。",
    "process": "页面事实：充值中心同视口，套餐与热门充值入口基本一致，金额档位展示有轻微差异。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "充值套餐入口稳定，疑似金额档位展示微调。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0014/R0054_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0014/R0054_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0015",
    "reviewId": "R0050",
    "dimension": "留存促活运营",
    "page": "购物频道-官方补贴",
    "conclusion": "手机/数码频道同视口，搜索词、主推活动和新品Banner从OPPO等切换为vivo/荣耀等。",
    "process": "页面事实：手机/数码频道同视口，搜索词、主推活动和新品Banner从OPPO等切换为vivo/荣耀等。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "手机频道品牌与活动投放更新。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0015/R0050_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0015/R0050_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0016",
    "reviewId": "R0032",
    "dimension": "客服",
    "page": "消息分类-服务",
    "conclusion": "服务提醒空状态页一致，均显示暂无相关消息。",
    "process": "页面事实：服务提醒空状态页一致，均显示暂无相关消息。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "无明显变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0016/R0032_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0016/R0032_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0017",
    "reviewId": "R0028",
    "dimension": "客服",
    "page": "在线客服聊天页",
    "conclusion": "在线客服页同视口，热门问题与底部输入区基本一致。",
    "process": "页面事实：在线客服页同视口，热门问题与底部输入区基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "客服入口体验稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0017/R0028_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0017/R0028_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0019",
    "reviewId": "R0033",
    "dimension": "客服",
    "page": "微信公众号关注引导页",
    "conclusion": "关注分期乐服务号引导页一致，顶部banner、步骤说明、底部按钮无明显变化。",
    "process": "页面事实：关注分期乐服务号引导页一致，顶部banner、步骤说明、底部按钮无明显变化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "客服/公众号引导链路稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0019/R0033_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0019/R0033_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0020",
    "reviewId": "R0029",
    "dimension": "风控",
    "page": "更多服务入口页",
    "conclusion": "更多服务页同视口，借款服务与推荐服务布局基本一致。",
    "process": "页面事实：更多服务页同视口，借款服务与推荐服务布局基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "服务入口稳定，无明显变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0020/R0029_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0020/R0029_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0021",
    "reviewId": "R0051",
    "dimension": "风控",
    "page": "我的页-设置",
    "conclusion": "设置页同视口，菜单项、顺序、开关状态基本一致。",
    "process": "页面事实：设置页同视口，菜单项、顺序、开关状态基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "设置页稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0021/R0051_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0021/R0051_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0023",
    "reviewId": "R0052",
    "dimension": "风控",
    "page": "我的页-黑产举报",
    "conclusion": "金融黑灰产举报/科普页同视口，主视觉、文案、卡片和举报按钮基本一致。",
    "process": "页面事实：金融黑灰产举报/科普页同视口，主视觉、文案、卡片和举报按钮基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "风控/反诈宣导页稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0023/R0052_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0023/R0052_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0025",
    "reviewId": "R0053",
    "dimension": "消金",
    "page": "还款记录页",
    "conclusion": "还款记录页同视口，Tab与空状态一致。",
    "process": "页面事实：还款记录页同视口，Tab与空状态一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "还款记录空状态稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0025/R0053_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0025/R0053_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0026",
    "reviewId": "R0060",
    "dimension": "消金",
    "page": "自动还款设置页",
    "conclusion": "自动还款设置页同视口，布局、开关状态、说明文案基本一致。",
    "process": "页面事实：自动还款设置页同视口，布局、开关状态、说明文案基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "自动还款设置链路稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0026/R0060_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0026/R0060_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0029",
    "reviewId": "R0034",
    "dimension": "消金",
    "page": "服务大厅/订单售后FAQ",
    "conclusion": "服务大厅订单售后FAQ页面一致，问题列表与底部在线咨询按钮基本不变。",
    "process": "页面事实：服务大厅订单售后FAQ页面一致，问题列表与底部在线咨询按钮基本不变。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "客服自助答疑入口稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0029/R0034_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0029/R0034_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0034",
    "reviewId": "R0035",
    "dimension": "客服",
    "page": "卡券页",
    "conclusion": "卡券-优惠券空状态页一致，暂无优惠券与兑换码入口一致。",
    "process": "页面事实：卡券-优惠券空状态页一致，暂无优惠券与兑换码入口一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "优惠券空状态和兑换入口稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0034/R0035_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0034/R0035_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0035",
    "reviewId": "R0047",
    "dimension": "客服",
    "page": "额度频道页",
    "conclusion": "额度中心同视口，新增/露出PLUS服务专属提额券卡片与去领取按钮。",
    "process": "页面事实：额度中心同视口，新增/露出PLUS服务专属提额券卡片与去领取按钮。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "额度中心强化会员提额权益转化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0035/R0047_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0035/R0047_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "分期乐",
    "appKey": "fenqile",
    "materialId": "fenqile-0042",
    "reviewId": "R0049",
    "dimension": "客服",
    "page": "首页推荐页",
    "conclusion": "首页同视口，部分商品活动改为提额、审批服务、爆款特权等权益卡片。",
    "process": "页面事实：首页同视口，部分商品活动改为提额、审批服务、爆款特权等权益卡片。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "首页运营策略偏金融权益/提额服务。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0042/R0049_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/fenqile/fenqile-0042/R0049_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0018",
    "reviewId": "R0154",
    "dimension": "留存促活运营",
    "page": "理财首页",
    "conclusion": "理财首页同一页面，首屏运营内容大幅变化：新用户高收益卡片变为限时奖励/榜单推荐。",
    "process": "页面事实：理财首页同一页面，首屏运营内容大幅变化：新用户高收益卡片变为限时奖励/榜单推荐。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "中",
    "managementUsable": true,
    "managementNote": "理财首页运营位和推荐策略明显调整。（影响等级复核：中）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0018/R0154_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0018/R0154_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0002",
    "reviewId": "R0155",
    "dimension": "消金",
    "page": "借款金额输入页",
    "conclusion": "借款金额输入页和数字键盘布局基本一致。",
    "process": "页面事实：借款金额输入页和数字键盘布局基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "无明显业务变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0002/R0155_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0002/R0155_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0006",
    "reviewId": "R0396",
    "dimension": "风控",
    "page": "借钱额度页",
    "conclusion": "借钱额度页结构一致；顶部提示、额度文案、优惠有效天数和节省金额变化。",
    "process": "页面事实：借钱额度页结构一致；顶部提示、额度文案、优惠有效天数和节省金额变化。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "借款额度页营销文案和优惠信息调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0006/R0396_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0006/R0396_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0007",
    "reviewId": "R0192",
    "dimension": "消金",
    "page": "借钱首页/额度页",
    "conclusion": "借钱频道页同屏，额度不变；活动倒计时由13天变7天，优惠期限由14天变8天。",
    "process": "页面事实：借钱频道页同屏，额度不变；活动倒计时由13天变7天，优惠期限由14天变8天。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "借款优惠活动时效缩短。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0007/R0192_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0007/R0192_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0008",
    "reviewId": "R0408",
    "dimension": "留存促活运营",
    "page": "保险频道页",
    "conclusion": "保险首页同一视口，分类、健康礼包卡片和导航基本一致。",
    "process": "页面事实：保险首页同一视口，分类、健康礼包卡片和导航基本一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "保险频道主推路径稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0008/R0408_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0008/R0408_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0009",
    "reviewId": "R0415",
    "dimension": "风控",
    "page": "我的/账户页",
    "conclusion": "左右均为同一我的/个人中心页面，主体布局、模块内容、按钮与导航基本一致。",
    "process": "页面事实：左右均为同一我的/个人中心页面，主体布局、模块内容、按钮与导航基本一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "未发现影响业务流程或用户理解的页面变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0009/R0415_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0009/R0415_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0012",
    "reviewId": "R0406",
    "dimension": "留存促活运营",
    "page": "保险频道首页",
    "conclusion": "保险页新人礼包区域匹配，入口、健康礼包卡片和导航位置一致。",
    "process": "页面事实：保险页新人礼包区域匹配，入口、健康礼包卡片和导航位置一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "保险频道展示稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0012/R0406_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0012/R0406_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0013",
    "reviewId": "R0203",
    "dimension": "消金",
    "page": "额度基础问题及提额攻略页",
    "conclusion": "额度攻略说明页同一视口，标题、插画、文案和按钮基本一致。",
    "process": "页面事实：额度攻略说明页同一视口，标题、插画、文案和按钮基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "页面展示稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0013/R0203_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0013/R0203_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0014",
    "reviewId": "R0022",
    "dimension": "消金",
    "page": "借款申请步骤攻略页",
    "conclusion": "借款申请步骤说明页标题、插画、说明内容和底部按钮基本一致。",
    "process": "页面事实：借款申请步骤说明页标题、插画、说明内容和底部按钮基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "未观察到有效业务视觉变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0014/R0022_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0014/R0022_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0017",
    "reviewId": "R0149",
    "dimension": "风控",
    "page": "提额降息中心详情页",
    "conclusion": "提额降息中心布局、额度、年利率、按钮和列表基本一致。",
    "process": "页面事实：提额降息中心布局、额度、年利率、按钮和列表基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "未观察到明确业务视觉变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0017/R0149_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0017/R0149_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0020",
    "reviewId": "R0409",
    "dimension": "留存促活运营",
    "page": "保险定制页",
    "conclusion": "保险定制方案落地页同一视口，主视觉、预约按钮和布局基本一致。",
    "process": "页面事实：保险定制方案落地页同一视口，主视觉、预约按钮和布局基本一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "继续推广1对1保险定制咨询服务。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0020/R0409_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0020/R0409_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0021",
    "reviewId": "R0194",
    "dimension": "风控",
    "page": "借钱额度页",
    "conclusion": "借钱首页同屏，额度不变；恢复额度倒计时、优惠期限和省钱金额变化。",
    "process": "页面事实：借钱首页同屏，额度不变；恢复额度倒计时、优惠期限和省钱金额变化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "核心借款优惠金额和活动时效变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0021/R0194_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0021/R0194_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0027",
    "reviewId": "R0400",
    "dimension": "风控",
    "page": "借钱页下滑/新人指南",
    "conclusion": "借钱页中部模块视口匹配，提额降息、新人指南、保障信息和理财入口区域一致。",
    "process": "页面事实：借钱页中部模块视口匹配，提额降息、新人指南、保障信息和理财入口区域一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "中部运营模块稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0027/R0400_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0027/R0400_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0028",
    "reviewId": "R0141",
    "dimension": "风控",
    "page": "借钱额度页",
    "conclusion": "同一借钱主页面，额度一致；优惠有效期由12天变6天，节省金额明显变化。",
    "process": "页面事实：同一借钱主页面，额度一致；优惠有效期由12天变6天，节省金额明显变化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "核心借款优惠展示变化，可能影响价格优惠感知。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0028/R0141_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0028/R0141_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0029",
    "reviewId": "R0402",
    "dimension": "风控",
    "page": "借钱页下滑/新人指南",
    "conclusion": "借钱页中部内容匹配，模块顺序和可见内容一致。",
    "process": "页面事实：借钱页中部内容匹配，模块顺序和可见内容一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "中部页面结构稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0029/R0402_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0029/R0402_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0031",
    "reviewId": "R0018",
    "dimension": "风控",
    "page": "理财产品推荐页",
    "conclusion": "理财首页首屏结构变化：顶部账户/收益数据区、新手限时权益卡片和推荐模块调整，收益率小幅变化。",
    "process": "页面事实：理财首页首屏结构变化：顶部账户/收益数据区、新手限时权益卡片和推荐模块调整，收益率小幅变化。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "理财首页运营位与新客转化入口调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0031/R0018_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0031/R0018_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0038",
    "reviewId": "R0144",
    "dimension": "风控",
    "page": "借钱页下半屏",
    "conclusion": "同一页面相近视口，新人指南和理财券模块一致；中部横幅由绿色助农免息变为橙色保障信息。",
    "process": "页面事实：同一页面相近视口，新人指南和理财券模块一致；中部横幅由绿色助农免息变为橙色保障信息。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "营销/任务引导横幅切换。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0038/R0144_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0038/R0144_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "度小满",
    "appKey": "duxiaoman",
    "materialId": "duxiaoman-0039",
    "reviewId": "R0405",
    "dimension": "消金",
    "page": "借钱页新人指南",
    "conclusion": "借钱页中下部理财券区域匹配，红色中奖横幅、理财券卡片及底部导航一致。",
    "process": "页面事实：借钱页中下部理财券区域匹配，红色中奖横幅、理财券卡片及底部导航一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "中下部运营区域稳定。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0039/R0405_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/duxiaoman/duxiaoman-0039/R0405_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0001",
    "reviewId": "R0286",
    "dimension": "消金",
    "page": "借钱首页",
    "conclusion": "视觉确认左右均为借钱首页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为借钱首页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0001/R0286_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0001/R0286_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0002",
    "reviewId": "R0287",
    "dimension": "消金",
    "page": "借钱首页-下滑一屏",
    "conclusion": "视觉确认左右均为借钱首页-下滑一屏，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为借钱首页-下滑一屏，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0002/R0287_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0002/R0287_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0004",
    "reviewId": "R0388",
    "dimension": "消金",
    "page": "服务页/还款查账与富能协议",
    "conclusion": "视觉确认左右均为服务页/还款查账与富能协议，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为服务页/还款查账与富能协议，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0004/R0388_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0004/R0388_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0006",
    "reviewId": "R0288",
    "dimension": "消金",
    "page": "借钱首页-下滑一屏",
    "conclusion": "视觉确认左右均为借钱首页-下滑一屏，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为借钱首页-下滑一屏，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0006/R0288_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0006/R0288_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0009",
    "reviewId": "R0184",
    "dimension": "消金",
    "page": "我的/账户页",
    "conclusion": "视觉确认左右均为我的/账户页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为我的/账户页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0009/R0184_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0009/R0184_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0011",
    "reviewId": "R0289",
    "dimension": "消金",
    "page": "借钱首页-下滑一屏",
    "conclusion": "视觉确认左右均为借钱首页-下滑一屏，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为借钱首页-下滑一屏，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0011/R0289_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0011/R0289_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0012",
    "reviewId": "R0389",
    "dimension": "消金",
    "page": "服务页/还款查账与富能福利",
    "conclusion": "视觉确认左右均为服务页/还款查账与富能福利，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为服务页/还款查账与富能福利，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0012/R0389_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0012/R0389_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0023",
    "reviewId": "R0186",
    "dimension": "风控",
    "page": "我的-消费者权益保护",
    "conclusion": "视觉确认左右均为我的-消费者权益保护，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为我的-消费者权益保护，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为风控维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0023/R0186_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0023/R0186_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0028",
    "reviewId": "R0320",
    "dimension": "消金",
    "page": "我的一级页下滑 / 0428我的页2",
    "conclusion": "视觉确认左右均为我的一级页下滑 / 0428我的页2，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为我的一级页下滑 / 0428我的页2，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0028/R0320_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0028/R0320_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0029",
    "reviewId": "R0378",
    "dimension": "消金",
    "page": "服务一级页下滑 / 0428服务页2",
    "conclusion": "视觉确认左右均为服务一级页下滑 / 0428服务页2，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为服务一级页下滑 / 0428服务页2，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0029/R0378_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0029/R0378_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0035",
    "reviewId": "R0239",
    "dimension": "消金",
    "page": "我的/个人中心页",
    "conclusion": "视觉确认左右均为我的/个人中心页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为我的/个人中心页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0035/R0239_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0035/R0239_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "奇富借条",
    "appKey": "qifu",
    "materialId": "qifu-0039",
    "reviewId": "R0292",
    "dimension": "风控",
    "page": "风控/借钱页2",
    "conclusion": "视觉确认左右均为风控/借钱页2，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为风控/借钱页2，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为风控维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0039/R0292_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/qifu/qifu-0039/R0292_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0001",
    "reviewId": "R0284",
    "dimension": "风控",
    "page": "借款首页/额度页",
    "conclusion": "同一借款首页，布局与位置一致。",
    "process": "页面事实：同一借款首页，布局与位置一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0001/R0284_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0001/R0284_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0002",
    "reviewId": "R0279",
    "dimension": "风控",
    "page": "借款首页下滑/品牌介绍",
    "conclusion": "同一首页，布局一致，仅时间/角标差异。",
    "process": "页面事实：同一首页，布局一致，仅时间/角标差异。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0002/R0279_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0002/R0279_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0003",
    "reviewId": "R0282",
    "dimension": "消金",
    "page": "我的/个人中心首页首屏",
    "conclusion": "同一我的页，仅问候语/时间变化。",
    "process": "页面事实：同一我的页，仅问候语/时间变化。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0003/R0282_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0003/R0282_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0007",
    "reviewId": "R0439",
    "dimension": "留存促活运营",
    "page": "活动中心/我的钱包",
    "conclusion": "活动中心页面一致。",
    "process": "页面事实：活动中心页面一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0007/R0439_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0007/R0439_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0008",
    "reviewId": "R0283",
    "dimension": "留存促活运营",
    "page": "天天签到/抽奖活动页",
    "conclusion": "同一签到/抽奖页，仅开奖号/金额动态变化。",
    "process": "页面事实：同一签到/抽奖页，仅开奖号/金额动态变化。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0008/R0283_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0008/R0283_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0011",
    "reviewId": "R0280",
    "dimension": "消金",
    "page": "好友出额/提额邀请活动",
    "conclusion": "同一邀请提额页，仅文案/时间动态变化。",
    "process": "页面事实：同一邀请提额页，仅文案/时间动态变化。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0011/R0280_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0011/R0280_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0012",
    "reviewId": "R0285",
    "dimension": "消金",
    "page": "邀请赚现金活动",
    "conclusion": "同一邀请有礼页，仅倒计时/金额动态变化。",
    "process": "页面事实：同一邀请有礼页，仅倒计时/金额动态变化。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0012/R0285_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0012/R0285_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0013",
    "reviewId": "R0281",
    "dimension": "消金",
    "page": "助微免息计划/好友助力借款",
    "conclusion": "同一助微计划页，内容结构一致。",
    "process": "页面事实：同一助微计划页，内容结构一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0013/R0281_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0013/R0281_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "拍拍贷借款",
    "appKey": "paipai",
    "materialId": "paipai-0014",
    "reviewId": "R0278",
    "dimension": "留存促活运营",
    "page": "活动中心/待生效奖励明细页",
    "conclusion": "奖励明细空页一致。",
    "process": "页面事实：奖励明细空页一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0014/R0278_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/paipai/paipai-0014/R0278_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0006",
    "reviewId": "R0463",
    "dimension": "风控",
    "page": "借款首页/额度展示",
    "conclusion": "同为安逸花借款/贷款入口页同视口，主卡片、按钮与底部导航一致。",
    "process": "页面事实：同为安逸花借款/贷款入口页同视口，主卡片、按钮与底部导航一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花借款首页/额度展示的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0006/R0463_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0006/R0463_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0007",
    "reviewId": "R0466",
    "dimension": "风控",
    "page": "wide-风控 / 我的 / 我的",
    "conclusion": "同为安逸花“我的”页顶部同一视口，布局一致，仅动态文案/时间不同。",
    "process": "页面事实：同为安逸花“我的”页顶部同一视口，布局一致，仅动态文案/时间不同。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花wide-风控 / 我的 / 我的的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0007/R0466_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0007/R0466_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0008",
    "reviewId": "R0001",
    "dimension": "风控",
    "page": "wide-风控 / 提额 / 额度成长",
    "conclusion": "同为额度成长/涨分任务类页面，同一视口，主体结构一致，仅时间/数值等轻微动态差异。",
    "process": "页面事实：同为额度成长/涨分任务类页面，同一视口，主体结构一致，仅时间/数值等轻微动态差异。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花wide-风控 / 提额 / 额度成长的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0008/R0001_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0008/R0001_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0011",
    "reviewId": "R0467",
    "dimension": "风控",
    "page": "首页/品牌与风险提示信息流",
    "conclusion": "同为安逸花首页顶部同一视口，核心模块和位置一致。",
    "process": "页面事实：同为安逸花首页顶部同一视口，核心模块和位置一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花首页/品牌与风险提示信息流的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0011/R0467_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0011/R0467_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0014",
    "reviewId": "R0004",
    "dimension": "留存促活运营",
    "page": "wide-留存促活运营 / 我的-商品优惠券",
    "conclusion": "同为“我的优惠券-商品券”空状态页，视口与状态一致，仅状态栏等动态差异。",
    "process": "页面事实：同为“我的优惠券-商品券”空状态页，视口与状态一致，仅状态栏等动态差异。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花wide-留存促活运营 / 我的-商品优惠券的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0014/R0004_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0014/R0004_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0022",
    "reviewId": "R0161",
    "dimension": "风控",
    "page": "material scroll-0 / 我的页下半截",
    "conclusion": "同为“我的”页同一滚动视口，模块布局和内容基本一致。",
    "process": "页面事实：同为“我的”页同一滚动视口，模块布局和内容基本一致。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花material scroll-0 / 我的页下半截的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0022/R0161_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0022/R0161_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "安逸花",
    "appKey": "anyihua",
    "materialId": "anyihua-0025",
    "reviewId": "R0473",
    "dimension": "风控",
    "page": "material bottom-108 tap-我的 / 我的页",
    "conclusion": "左右均为安逸花“我的”页且视口位置一致，可进行严格对比。",
    "process": "页面事实：左右均为安逸花“我的”页且视口位置一致，可进行严格对比。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入安逸花material bottom-108 tap-我的 / 我的页的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0025/R0473_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/anyihua/anyihua-0025/R0473_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "京东金融",
    "appKey": "jdjr",
    "materialId": "jdjr-0009",
    "reviewId": "R0267",
    "dimension": "消金",
    "page": "全部服务页",
    "conclusion": "视觉确认左右均为全部服务页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为全部服务页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0009/R0267_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0009/R0267_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "京东金融",
    "appKey": "jdjr",
    "materialId": "jdjr-0011",
    "reviewId": "R0063",
    "dimension": "消金",
    "page": "金条借款额度激活页",
    "conclusion": "视觉确认左右均为金条借款额度激活页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为金条借款额度激活页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为消金维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0011/R0063_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0011/R0063_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "京东金融",
    "appKey": "jdjr",
    "materialId": "jdjr-0012",
    "reviewId": "R0268",
    "dimension": "留存促活运营",
    "page": "京东保/保险首页",
    "conclusion": "视觉确认左右均为京东保/保险首页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为京东保/保险首页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为留存促活运营维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0012/R0268_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0012/R0268_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "京东金融",
    "appKey": "jdjr",
    "materialId": "jdjr-0013",
    "reviewId": "R0064",
    "dimension": "风控",
    "page": "白条额度更新结果页",
    "conclusion": "视觉确认左右均为白条额度更新结果页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为白条额度更新结果页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为风控维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0013/R0064_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0013/R0064_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "京东金融",
    "appKey": "jdjr",
    "materialId": "jdjr-0016",
    "reviewId": "R0209",
    "dimension": "风控",
    "page": "签到领现金活动页",
    "conclusion": "视觉确认左右均为签到领现金活动页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为签到领现金活动页，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为风控维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0016/R0209_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0016/R0209_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "京东金融",
    "appKey": "jdjr",
    "materialId": "jdjr-0044",
    "reviewId": "R0080",
    "dimension": "留存促活运营",
    "page": "首页/内容与保险推荐",
    "conclusion": "视觉确认左右均为首页/内容与保险推荐，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。",
    "process": "页面事实：视觉确认左右均为首页/内容与保险推荐，同APP、同入口/功能且滚动视口基本一致；可进入业务变化分析。\n判定理由：已完成 0530 与 0605 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为留存促活运营维度可比证据，重点观察运营文案、金额/权益、模块排序等实际变化。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0044/R0080_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/jdjr/jdjr-0044/R0080_0605.png",
    "latestDate": "0605"
  },
  {
    "app": "马上金融",
    "appKey": "mashang",
    "materialId": "mashang-0002",
    "reviewId": "R0271",
    "dimension": "消金",
    "page": "运营页首页",
    "conclusion": "同一商城/活动页面同视口，内容基本一致。",
    "process": "页面事实：同一商城/活动页面同视口，内容基本一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/mashang/mashang-0002/R0271_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/mashang/mashang-0002/R0271_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "马上金融",
    "appKey": "mashang",
    "materialId": "mashang-0004",
    "reviewId": "R0449",
    "dimension": "消金",
    "page": "首页启动页",
    "conclusion": "同为首页顶部/启动视口，核心内容一致。",
    "process": "页面事实：同为首页顶部/启动视口，核心内容一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/mashang/mashang-0004/R0449_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/mashang/mashang-0004/R0449_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "马上金融",
    "appKey": "mashang",
    "materialId": "mashang-0021",
    "reviewId": "R0276",
    "dimension": "消金",
    "page": "消金页面下滑页",
    "conclusion": "页面与状态基本一致，可作同视口对比。",
    "process": "页面事实：页面与状态基本一致，可作同视口对比。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可作为同页面同视口的稳定/变化证据，适合进入HTML对比。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/mashang/mashang-0021/R0276_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/mashang/mashang-0021/R0276_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "小赢卡贷",
    "appKey": "xiaoying",
    "materialId": "xiaoying-0003",
    "reviewId": "R0297",
    "dimension": "风控",
    "page": "风险监测/风险查询页",
    "conclusion": "左右均为“风险查询”页，同入口同视口，主体布局与内容一致。",
    "process": "页面事实：左右均为“风险查询”页，同入口同视口，主体布局与内容一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入小赢卡贷风险监测/风险查询页的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/xiaoying/xiaoying-0003/R0297_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/xiaoying/xiaoying-0003/R0297_0606.png",
    "latestDate": "0606"
  },
  {
    "app": "小赢卡贷",
    "appKey": "xiaoying",
    "materialId": "xiaoying-0011",
    "reviewId": "R0367",
    "dimension": "风控",
    "page": "设置页",
    "conclusion": "左右均为“设置”页，同一列表结构与条目一致，视口范围一致。",
    "process": "页面事实：左右均为“设置”页，同一列表结构与条目一致，视口范围一致。\n判定理由：已完成 0530 与 0606 截图左右视觉复查，判定为同 APP、同页面/入口、同视口 strict 可比。\n边界说明：动态金额、登录态、系统时间、角标、开奖码等不单独归因为产品改版；错页/视口不一致样本已剔除。",
    "impact": "低",
    "managementUsable": false,
    "managementNote": "可纳入小赢卡贷设置页的可比变化证据；重点观察页面布局、入口位置、权益/额度/风控文案是否调整。（影响等级复核：低）",
    "before": "/evidence/0530-0605-0606-all-mapped/xiaoying/xiaoying-0011/R0367_0530.png",
    "after": "/evidence/0530-0605-0606-all-mapped/xiaoying/xiaoying-0011/R0367_0606.png",
    "latestDate": "0606"
  }
]

export const appReportSummaries = [
  {
    "product": "分期乐",
    "strictCount": 27,
    "managementCount": 4,
    "high": 0,
    "medium": 4,
    "low": 23,
    "mainStrategy": "分期乐 strict 对照多，但多数为消息/商品/PLUS 等页面的内容或状态变化；稳定页和商品列表类更新已按低影响处理，仅金融权益/审批服务/返券等承接方向变化保留中影响。 可分析维度：风控6、消金10、留存促活运营1、客服10。",
    "reportBoundary": "全部候选复查 66 条：strict 30、错页 31、视口不一致 0、状态边界 5；HTML 去重保留 27 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "度小满",
    "strictCount": 18,
    "managementCount": 1,
    "high": 0,
    "medium": 1,
    "low": 17,
    "mainStrategy": "度小满变化集中在促销横幅、额度/免息/权益文案等运营内容，稳定/动态状态样本已降为低影响。 可分析维度：留存促活运营4、风控9、消金5。",
    "reportBoundary": "全部候选复查 105 条：strict 50、错页 31、视口不一致 11、状态边界 13；HTML 去重保留 18 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "奇富借条",
    "strictCount": 12,
    "managementCount": 0,
    "high": 0,
    "medium": 0,
    "low": 12,
    "mainStrategy": "奇富可比样本多为页面对齐或轻量运营变化，未见足够证据判高；稳定与泛化观察按低影响处理。 可分析维度：消金10、风控2。",
    "reportBoundary": "全部候选复查 90 条：strict 17、错页 43、视口不一致 8、状态边界 22；HTML 去重保留 12 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "拍拍贷借款",
    "strictCount": 9,
    "managementCount": 0,
    "high": 0,
    "medium": 0,
    "low": 9,
    "mainStrategy": "拍拍贷整体结构稳定，邀请/活动动态类变化多数按低影响处理。 可分析维度：风控2、消金4、留存促活运营3。",
    "reportBoundary": "全部候选复查 40 条：strict 26、错页 11、视口不一致 1、状态边界 2；HTML 去重保留 9 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "安逸花",
    "strictCount": 7,
    "managementCount": 0,
    "high": 0,
    "medium": 0,
    "low": 7,
    "mainStrategy": "安逸花可比样本主要是额度成长/账户页等稳定或轻量变化。 可分析维度：风控6、留存促活运营1。",
    "reportBoundary": "全部候选复查 28 条：strict 13、错页 13、视口不一致 0、状态边界 2；HTML 去重保留 7 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "京东金融",
    "strictCount": 6,
    "managementCount": 0,
    "high": 0,
    "medium": 0,
    "low": 6,
    "mainStrategy": "京东变化集中在首页运营位和服务页展示，未见核心主链路变化。 可分析维度：消金2、留存促活运营2、风控2。",
    "reportBoundary": "全部候选复查 55 条：strict 12、错页 29、视口不一致 0、状态边界 14；HTML 去重保留 6 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "马上金融",
    "strictCount": 3,
    "managementCount": 0,
    "high": 0,
    "medium": 0,
    "low": 3,
    "mainStrategy": "马上金融主要为登录态/动态状态与稳定样本。 可分析维度：消金3。",
    "reportBoundary": "全部候选复查 38 条：strict 3、错页 9、视口不一致 14、状态边界 12；HTML 去重保留 3 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  },
  {
    "product": "小赢卡贷",
    "strictCount": 2,
    "managementCount": 0,
    "high": 0,
    "medium": 0,
    "low": 2,
    "mainStrategy": "小赢可比样本少，主要支持风险查询页稳定和轻量观察。 可分析维度：风控2。",
    "reportBoundary": "全部候选复查 51 条：strict 2、错页 49、视口不一致 0、状态边界 0；HTML 去重保留 2 组。；影响等级已按“高=主任务/核心入口/新增转化位，中=模块替换/承接调整，低=轻微展示/动态数据”重算。；已修正稳定/无明显变化样本误判中影响的问题。"
  }
]
